### ISSUE TITLE
v0.2.1 build unsuccessful

### ISSUE THREAD

**Issue by einsweniger** [vitiral/rst#15] opened 2016-11-23 17:56 UTC
Sorry to say, I am not fluent in rust, nor can I make any sense of the error I got.

```
error[E0277]: the trait bound `T: std::clone::Clone` is not satisfied
  --> /home/rawr/.cargo/registry/src/github.com-1ecc6299db9ec823/rst_app-0.2.1/src/cmd/matches.rs:33:10
   |
33 |         .get_matches_from_safe(args)
   |          ^^^^^^^^^^^^^^^^^^^^^ trait `T: std::clone::Clone` not satisfied
   |
   = help: consider adding a `where T: std::clone::Clone` bound

```
I am building with cargo 14.0 and rust 1.13.0 under Archlinux, will provide more information if necessary.
(you might also want to change the project description from rst to rst_app )

**Comment by vitiral** [comment] 2016-11-25 15:11
Hey, thanks for the issue. I will look into it shortly. Until then, have you tried downloading the binary?

**Comment by vitiral** [comment] 2016-11-25 15:34
Bug is confirmed, I suspect that `clap` may have changed an API from under us.

I'll work on fixing this. Until then, you should be able to download the [linux binary](https://github.com/vitiral/rst#linux-binary) -- that is the main way that I install the app for arch linux.

Thanks for the bug report!

**Comment by vitiral** [comment] 2016-11-26 05:21
caused by kbknapp/clap-rs#738, will be fixed in next release (shortly)

**Closed** 2016-11-26 05:21 UTC
Labels: bug
